### ISSUE TITLE
Catch and handle exception when no URL can be generated

### ISSUE THREAD

**Issue by JayReturns** [lociii/homeassistant-csgo#14]
Hello,

after installing the addon using HACS, I followed the instructions in order to set up the addon. I went to Configuration > Integration and added the csgo-integration. After clicking on "submit" it creates an error:

![grafik](https://user-images.githubusercontent.com/25531620/144264278-c9d8083a-c4ab-4aec-9d45-85430f1c2aa9.png)

The logs do not provide any info about the error. 

What can I do to set up the integration correctly?
Thanks in advance

**Comment by JayReturns** [comment]
I fixed the issue. After having an even closer look at the logs, i noticed the following one:

    Logger: aiohttp.server
    Source: helpers/network.py:116
    First occurred: 16:27:18 (25 occurrences)
    Last logged: 16:39:14
    
    Error handling request
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
        resp = await self._request_handler(request)
      File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
        resp = await handler(request)
      File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
        return await handler(request)
      File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
        result = await result
      File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
        return await super().post(request, flow_id)
      File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
        result = await method(view, request, *args, **kwargs)
      File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
        result = await self._flow_mgr.async_configure(flow_id, data)
      File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
        result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
      File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
        result: FlowResult = await getattr(flow, method)(user_input)
      File "/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py", line 173, in async_step_user
        webhook_url = self.hass.components.webhook.async_generate_url(webhook_id)
      File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 69, in async_generate_url
        get_url(hass, prefer_external=True, allow_cloud=False),
      File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
        raise NoURLAvailableError
    homeassistant.helpers.network.NoURLAvailableError


HA was unable to get a url. I had to add my external url in Configuration > General > External URL.

**Comment by lociii** [comment]
Let me re-open this one as the error should be caught so that other users get a proper message instead of "Unknown error".
I'll see if I can take care of it next few days.

Thanks for reporting!

**Comment by lociii** [comment]
This is unfortunately internal handling of Home Assistant when a webhook setup cannot generate a URL. Nothing we can do about it in this integration. Will update the documentation that URLs need to be configured.
